### ISSUE TITLE
Unable to get children of dc=abc,dc=xyz: missing paged control

### ISSUE THREAD

**Issue by iamGavinJ** [fengtan/ldap-explorer#56]
Unable to expand the tree view.  It throws the error:
Unable to get children of dc=abc,dc=xyz: missing paged control

**Comment by fengtan** [comment]
Thanks for the report @iamGavinJ !

It sounds like your LDAP server does not support paged search https://github.com/ldapjs/node-ldapjs/blob/v2.3.3/lib/client/search_pager.js#L90-L93

What software powers your LDAP server? (Active Directory,  OpenLDAP...)
Would you be able to check whether your LDAP server supports paged search?

**Comment by iamGavinJ** [comment]
Thanks for the quick reply. I'm running lldap; It's a new install.

I'll see if I can find out about pagination support.

**Comment by fengtan** [comment]
I can't find any documentation about pagination at https://github.com/lldap/lldap, so maybe lldap just does not support this feature.

I have just published pre-release [1.3.1-rc](https://github.com/fengtan/ldap-explorer/releases/tag/1.3.1-rc) which adds a new checkbox `Automatic result paging` when editing the connection details:
![automatic-result-paging](https://github.com/fengtan/ldap-explorer/assets/1483301/500bdec6-e706-475c-9997-56995e3a57b0).

The checkbox is checked by default for backwards-compatibility reasons (and also because most LDAP servers support pagination), but if you disable it then that might fix the problem.

@iamGavinJ would you be able to give it a try? You can download the the `.vsix` archive from the pre-release page and test it locally like this:

![install_vsix](https://user-images.githubusercontent.com/1483301/202880388-7a264240-76a3-49f7-9552-145573437a67.png)

**Comment by cass-e-design** [comment]
I just had the same issue, and this pre-release seems to be working great for me. Thanks!

**Comment by fengtan** [comment]
Thanks for testing!
I have just tagged [1.3.1](https://github.com/fengtan/ldap-explorer/releases/tag/1.3.1) and published to VS Code Marketplace.

**Comment by iamGavinJ** [comment]
Hi @fengtan, thanks for the fast turnaround.  I'm seeing the update on the VSC Marketplace, did the update, but I'm not able see the setting.  I rolled back to your -rc and also don't see the option:

![image](https://github.com/fengtan/ldap-explorer/assets/15910740/90b575bc-7c6d-4821-86c2-7b1cf47b7f20)

**Comment by fengtan** [comment]
Hey @iamGavinJ the setting is configured to show up the connection screen rather than the extension screen (some of your servers may support paged results while others may not so I made it connection-specific):

![ldap-explorer-automatic-result-paging](https://github.com/fengtan/ldap-explorer/assets/1483301/406343b3-234e-455d-b333-fe09ba9944c6)

**Comment by iamGavinJ** [comment]
urgh of course it is! 🤦🏻‍♂️

Sorry not enough caffeine this morning.

Can confirm, your update works perfectly!  Thanks so much.  And thanks also for developing this extension; You've really saved my workflow by not having to switch out to some clunky old CLI tool.  Really appreciate it!

**Comment by iamGavinJ** [comment]
Looks like disabling pagination might have caused some of your enumeration logic to fail to see the end of a tree:
![image](https://github.com/fengtan/ldap-explorer/assets/15910740/bdf20142-bce1-4b31-bc73-ea65bfeae27f)

Let me know if you'd prefer I open a new issue.

**Comment by fengtan** [comment]
Oh that is strange! Sure if you could open a new issue that would be great.

If you search the tree using another tool (e.g. [jXplorer](https://jxplorer.org/)), do you get the same behaviour?
